# Redmine公式イメージをベースにした Dockerfile
FROM redmine:5.1

# 使用する環境変数（Render上で設定可能）
ENV REDMINE_DB_MYSQL=REDMINE_DB_MYSQL_HOST \
    REDMINE_DB_USERNAME=REDMINE_DB_MYSQL_USER \
    REDMINE_DB_PASSWORD=REDMINE_DB_MYSQL_PASSWORD \
    REDMINE_DB_DATABASE=REDMINE_DB_MYSQL_DB \
    REDMINE_SECRET_TOKEN=secret_token

EXPOSE 3000
